# Generated by Django 4.2.11 on 2026-05-25 23:03

# pyrefly: ignore [missing-import]
from django.conf import settings
# pyrefly: ignore [missing-import]
from django.db import migrations, models
# pyrefly: ignore [missing-import]
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement'), ('UTILITY', 'Utility Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=10)),
                ('file_name', models.CharField(max_length=500)),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('suspicious_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_unit', models.CharField(max_length=50, unique=True)),
                ('canonical_unit', models.CharField(max_length=50)),
                ('conversion_factor', models.DecimalField(decimal_places=10, max_digits=20)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'Utility'), ('TRAVEL', 'Travel'), ('ALL', 'All')], default='ALL', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['source_unit'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='e.g. fuel_diesel, electricity_uk, flight_economy', max_length=100)),
                ('subcategory', models.CharField(blank=True, default='', max_length=100)),
                ('scope', models.CharField(choices=[('1', 'Scope 1'), ('2', 'Scope 2'), ('3', 'Scope 3')], max_length=1)),
                ('factor_kg_co2e_per_unit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('unit', models.CharField(help_text='Unit of the activity quantity, e.g. litre, kWh, km', max_length=50)),
                ('source', models.CharField(help_text='e.g. DEFRA 2023, EPA 2023', max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['scope', 'category'],
                'unique_together': {('category', 'subcategory', 'year')},
            },
        ),
        migrations.CreateModel(
            name='SourceRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField(help_text='1-indexed row number in the original file')),
                ('raw_payload', models.JSONField(help_text='Exact key-value pairs from the source row')),
                ('parse_status', models.CharField(choices=[('PARSED', 'Parsed OK'), ('FAILED', 'Parse Failed')], default='PARSED', max_length=10)),
                ('parse_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_rows', to='ingestion.ingestionbatch')),
            ],
            options={
                'ordering': ['batch', 'line_number'],
                'indexes': [models.Index(fields=['batch', 'parse_status'], name='ingestion_s_batch_i_c383ba_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ingestionbatch',
            index=models.Index(fields=['tenant', 'source_type'], name='ingestion_i_tenant__aee90f_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionbatch',
            index=models.Index(fields=['status'], name='ingestion_i_status_29a080_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionbatch',
            index=models.Index(fields=['-uploaded_at'], name='ingestion_i_uploade_2a7ecb_idx'),
        ),
    ]
