# Generated by Django 4.2.11 on 2026-05-25 23:03

# pyrefly: ignore [missing-import]
from django.conf import settings
# pyrefly: ignore [missing-import]
from django.db import migrations, models
# pyrefly: ignore [missing-import]
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement'), ('UTILITY', 'Utility Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=10)),
                ('category', models.CharField(choices=[('FUEL_DIESEL', 'Diesel'), ('FUEL_PETROL', 'Petrol / Gasoline'), ('FUEL_NATURAL_GAS', 'Natural Gas'), ('FUEL_LPG', 'LPG'), ('FUEL_HFO', 'Heavy Fuel Oil'), ('PROCUREMENT', 'Procurement (non-fuel)'), ('ELECTRICITY', 'Electricity'), ('FLIGHT', 'Flight'), ('HOTEL', 'Hotel Stay'), ('CAR_RENTAL', 'Car Rental / Ground Transport'), ('TRAIN', 'Train'), ('TAXI', 'Taxi / Rideshare'), ('UNKNOWN', 'Unknown / Unclassified')], default='UNKNOWN', max_length=30)),
                ('scope', models.CharField(blank=True, choices=[('1', 'Scope 1'), ('2', 'Scope 2'), ('3', 'Scope 3')], max_length=1, null=True)),
                ('activity_date', models.DateField(blank=True, help_text='The date the activity occurred (document date for SAP, period start for utility, trip date for travel)', null=True)),
                ('period_start', models.DateField(blank=True, help_text='For utility billing periods', null=True)),
                ('period_end', models.DateField(blank=True, help_text='For utility billing periods', null=True)),
                ('site', models.CharField(blank=True, default='', help_text='Resolved site name (after SiteMapping lookup)', max_length=255)),
                ('raw_site_code', models.CharField(blank=True, default='', help_text='Original code from source (SAP WERKS, meter ID, etc.)', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Original quantity exactly as parsed from source', max_digits=20, null=True)),
                ('unit', models.CharField(blank=True, default='', help_text='Original unit string from source', max_length=50)),
                ('normalized_quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Quantity converted to canonical unit', max_digits=20, null=True)),
                ('normalized_unit', models.CharField(blank=True, default='', help_text='Canonical unit after conversion (e.g. kWh, litres, km)', max_length=50)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, help_text='Estimated kg CO2e — indicative, not audited', max_digits=20, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('vendor', models.CharField(blank=True, default='', help_text='SAP vendor / travel merchant', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('reference_id', models.CharField(blank=True, default='', help_text='Original doc number / expense ID / meter ID for traceability', max_length=255)),
                ('cost_centre', models.CharField(blank=True, default='', max_length=100)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('origin', models.CharField(blank=True, default='', max_length=255)),
                ('destination', models.CharField(blank=True, default='', max_length=255)),
                ('traveler_name', models.CharField(blank=True, default='', max_length=255)),
                ('class_of_service', models.CharField(blank=True, default='', max_length=50)),
                ('hotel_nights', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged / Suspicious')], default='PENDING', max_length=10)),
                ('suspicious_flag', models.BooleanField(default=False)),
                ('suspicious_reasons', models.JSONField(blank=True, default=list, help_text='List of human-readable reasons the row was flagged')),
                ('locked_for_audit', models.BooleanField(default=False, help_text='True after approval — prevents further edits')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_activities', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ingestion.ingestionbatch')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_activities', to=settings.AUTH_USER_MODEL)),
                ('source_row', models.OneToOneField(blank=True, help_text='The raw row this was derived from. NULL if manually entered.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized_activity', to='ingestion.sourcerow')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Normalized Activities',
                'ordering': ['-activity_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'source_type'], name='normalizati_tenant__883e6f_idx'), models.Index(fields=['tenant', 'review_status'], name='normalizati_tenant__047ba4_idx'), models.Index(fields=['tenant', 'scope'], name='normalizati_tenant__6694ab_idx'), models.Index(fields=['suspicious_flag'], name='normalizati_suspici_db640a_idx'), models.Index(fields=['locked_for_audit'], name='normalizati_locked__0bc934_idx'), models.Index(fields=['-created_at'], name='normalizati_created_b653cc_idx')],
            },
        ),
    ]
