# Generated by Django 4.2.11 on 2026-05-25 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('INGEST', 'Ingested'), ('NORMALIZE', 'Normalized'), ('EDIT', 'Edited'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('UNLOCK', 'Unlocked')], max_length=15)),
                ('entity_type', models.CharField(help_text='Model name, e.g. NormalizedActivity', max_length=100)),
                ('entity_id', models.CharField(help_text='PK of the affected record as string', max_length=255)),
                ('before_json', models.JSONField(blank=True, help_text='Snapshot of relevant fields before the change', null=True)),
                ('after_json', models.JSONField(blank=True, help_text='Snapshot of relevant fields after the change', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action. NULL for system actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__0bff9a_idx'), models.Index(fields=['actor'], name='audit_audit_actor_i_40b234_idx'), models.Index(fields=['-timestamp'], name='audit_audit_timesta_3c72fe_idx')],
            },
        ),
    ]
